### ISSUE TITLE
no further output after "python train.py ..."

### ISSUE THREAD

**Issue by amiltonwong** [c-hofer/graph_filtration_learning#1]
Hi, @c-hofer ,

After generating the experiment configurations file, I run the following command as guided:

```
(pytorch1.4) root@milton-ThinkCentre-M93p:/data/code13/graph_filtration_learning# python train.py --cfg_file my_config.json --output_dir results --devices 0 --max_process_on_device 1
REDDIT-BINARY
/root2/anaconda3/envs/pytorch1.4/lib/python3.8/site-packages/torch/optim/lr_scheduler.py:118: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
```

However, it stays here without any further output. The GPU usage is around 3GB.

Any hints to fix this issue?

Thanks~

**Comment by c-hofer** [comment]
The results are pickled into the folder you give to the argument
`--output_dir`. The warning can be ignored. If the process does not die but
uses gpu capacity and no output is written then you have probably a
misconfigured gpu env. As you are running the code on a ThinkCentre you
probably just have to wait a long time to see any output. cheers c.

Am Mi., 10. März 2021 um 03:31 Uhr schrieb amiltonwong <
***@***.***>:

**Comment by amiltonwong** [comment]
Thanks @c-hofer . Finally, I see the output file xxx_model0.pt in `results` folder
